apiVersion: v1
kind: Service
metadata:
  name: dummy-service
  labels:
    app: dummy-app
spec:
  selector:
    app: dummy-app
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
